config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :message_rooms
  devise_for :users

  # action cable route
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#home'

  post 'message_rooms/subscribe'
  post 'message_rooms/:id', to: 'message_rooms#ajax_message'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :message_room

  validates_presence_of :body, :user_id, :message_room_id
end

app/models/message_room.rb
class MessageRoom < ApplicationRecord
  has_many :messages
  has_many :subscriptions
  has_many :users, through: :subscriptions

  validates_presence_of :title, :creator_id
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :message_room

  validates_presence_of :user_id, :message_room_id
end

app/models/user.rb
class User < ApplicationRecord

  has_many :messages
  has_many :subscriptions
  has_many :message_rooms, through: :subscriptions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:username]

  validates_uniqueness_of :username

  validates_presence_of :email, :username, :password

  def email_required?
   false
  end

  def email_changed?
   false
  end

  def initials
    return first_name[0,1].capitalize + last_name[0,1].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def home
    if user_signed_in?
      redirect_to '/message_rooms'
    end
  end

  protected

    # permitting username for strong params
    def configure_permitted_parameters
      added_attrs = [:username, :email, :password, :password_confirmation, :remember_me, :first_name, :last_name]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/message_rooms_controller.rb
class MessageRoomsController < ApplicationController
  before_action :set_message_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /message_rooms
  # GET /message_rooms.json
  def index
    @my_rooms = current_user.message_rooms.index_by(&:id)
    @all_message_rooms = MessageRoom.all
  end

  # GET /message_rooms/1
  # GET /message_rooms/1.json
  def show
    @messages = @message_room.messages.order(:created_at)
    @subscribers = @message_room.users
  end

  # GET /message_rooms/new
  def new
    @message_room = MessageRoom.new
  end

  # GET /message_rooms/1/edit
  def edit
  end

  # POST /message_rooms
  # POST /message_rooms.json
  def create
    @message_room = MessageRoom.new(message_room_params)

    respond_to do |format|
      if @message_room.save
        format.html { redirect_to @message_room, notice: 'Message room was successfully created.' }
        format.json { render :show, status: :created, location: @message_room }
      else
        format.html { render :new }
        format.json { render json: @message_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /message_rooms/1
  # PATCH/PUT /message_rooms/1.json
  def update
    respond_to do |format|
      if @message_room.update(message_room_params)
        format.html { redirect_to @message_room, notice: 'Message room was successfully updated.' }
        format.json { render :show, status: :ok, location: @message_room }
      else
        format.html { render :edit }
        format.json { render json: @message_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /message_rooms/1
  # DELETE /message_rooms/1.json
  def destroy
    @message_room.destroy
    respond_to do |format|
      format.html { redirect_to message_rooms_url, notice: 'Message room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def ajax_message
    @message = Message.new( body: params[:body],
                            user_id: params[:user_id],
                            message_room_id: params[:id])
    if @message.save
      ActionCable.server.broadcast 'messages',
        message: render_message(@message),
        room_id: @message.message_room_id
    end
  end

  def subscribe
    @subscription = Subscription.where(user_id: params[:user_id], message_room_id: params[:message_room_id])[0]

    # delete if subscription exists and create if it doesn't
    if @subscription
      @subscription.delete
    else
      Subscription.create(user_id: params[:user_id], message_room_id: params[:message_room_id])
    end

    # If the user subscribes on the page, redirect to page
    if params[:redirect_to_page]
      redirect_to "/message_rooms/#{params[:message_room_id]}"
      flash[:notice] = "you subscribed to this page!"
    else
      @my_rooms = current_user.message_rooms.index_by(&:id)
      respond_to :js
    end
  end

  private

    def set_message_room
      @message_room = MessageRoom.find(params[:id])
    end

    def message_room_params
      params.require(:message_room).permit(:title, :blurb, :creator_id)
    end

    # render comment for action cable function in #ajax_message
    def render_message(message)
        ApplicationController.render(partial: 'message_rooms/message',
                                     locals: { message: message, user: message.user })
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_rooms_helper.rb
module MessageRoomsHelper
end

app/views/application/_header.html.erb
<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <% if user_signed_in? %>
        <li>
          <h5 class="text-white h4"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></h5>
        </li>
      <% else %>
        <li>
          <h5 class="text-white h4"><%= link_to('Login', new_user_session_path) %></h5>
        </li>
      <% end %>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

app/views/application/home.html.erb
<div class="jumbotron">
  <h1 class="display-4">To all the messengers out there...</h1>
  <p class="lead">I built this app so you can chat with each other.</p>
  <hr class="my-4">
  <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageRoomApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- action cable tag -->
    <%= action_cable_meta_tag %>

    <!-- Bootstrap CDNs -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'header' %>
    <% if notice %>
      <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= notice.html_safe %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= alert.html_safe %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/message_rooms/_form.html.erb
<div class="w-75 m-auto">
  <%= form_with(model: message_room, local: true) do |form| %>
    <% if message_room.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(message_room.errors.count, "error") %> prohibited this message_room from being saved:</h2>

        <ul>
        <% message_room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :blurb %>
      <%= form.text_field :blurb, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.hidden_field :creator_id, value: current_user.id %>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary"%>
    </div>
  <% end %>

</div>

app/views/message_rooms/_message.html.erb
<div class="row">
  <div class="other-message-shell mr-auto">
    <div class="row px-4">
      <div class="message-initials">
        <%= user.username %>
      </div>
      <div class="message-body ml-5">
        <p class="ml-3"><%= message.body %>  - <i class="timestamp"><%= message.created_at%></i></p>
      </div>
    </div>
  </div>
</div>

app/views/message_rooms/_message_room_card.html.erb
<div class="col-md-4 col-sm-6 col-xs-12 mb-3">
  <div class="card m-1 h-100">
    <div class="card-header">
      <div class="row">
        <div class="col-12 mt-1">
          <h4 class="text-center mx-auto mb-0"><%=room.title%></h4>
        </div>
        <p class="col-12 text-center mt-0 mb-2">Subscribers: <%= room.users.count %></p>
        <div class="col-12 my-1">
          <div class="row justify-content-around">
            <% if @my_rooms[room.id] %>
              <%= link_to 'Unsubscribe',
                  message_rooms_subscribe_path(user_id: current_user.id, message_room_id: room.id),
                  remote: true,
                  method: :post,
                  class:"btn btn-outline-danger subscribe-button" %>
            <% else %>
              <%= link_to 'Subscribe',
                  message_rooms_subscribe_path(user_id: current_user.id, message_room_id: room.id),
                  remote: true,
                  method: :post,
                  class:"btn btn-outline-success subscribe-button" %>
            <% end %>
            <%= link_to 'enter', message_room_path(id: room.id), class:"btn btn-outline-primary" %>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body" id="subscribed-chats">
      <p><%=room.blurb%></p>
    </div>
  </div>
</div>

app/views/message_rooms/_my_rooms.html.erb
<% my_rooms.each do |key, value| %>
  <%= link_to message_room_path(value) do %>
    <div class="card card-body mb-2 text-dark">
      <h4><%= value.title %></h4>
      <br>
      Last message: <br>
      <%= value.messages.last ? value.messages.last.created_at : "never" %>
    </div>
  <% end %>
<% end %>

app/views/message_rooms/edit.html.erb
<h1 class="text-center my-5">Editing Message Room</h1>

<%= render 'form', message_room: @message_room %>

<%= link_to 'Show', @message_room %> |
<%= link_to 'Back', message_rooms_path %>

app/views/message_rooms/index.html.erb
<div class="message-home">
  <div class="row">
    <div class="col-sm-3 col-xs-12">
      <div class="card">
        <div class="card-header">
          <h3 class="text-center">My chats</h3>
        </div>
        <!-- iterate through users' followed rooms -->
        <div class="card-body" id="subscribed-chats">
          <%= render "my_rooms", my_rooms: @my_rooms %>
        </div>
      </div>
    </div>
    <div class="col-sm-9 col-xs-12">
      <div>
        <div class="card">
          <div class="card-header">
            <div class="row justify-content-center">
              <h2 class="text-center mr-3">All chats</h2>
              <%= link_to 'New Message Room', new_message_room_path, class: "btn btn-primary d-block my-auto" %>
            </div>
          </div>
          <div class="card-body p-5" id="subscribed-chats">
            <div class="row">
              <!-- iterate through all rooms -->
              <% @all_message_rooms.each do |room| %>
                <%= render partial:'message_room_card', locals: {room: room} %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- JS that changes the subscribe button when pressed -->
<script type="text/javascript">
  $(".subscribe-button").click((e) => {
    let element = $(e.target)
    if (element.hasClass("btn-outline-success")) {
      element.removeClass("btn-outline-success");
      element.addClass("btn-outline-danger");
      element.html("Unsubscribe");
    } else if (element.hasClass("btn-outline-danger")) {
      element.removeClass("btn-outline-danger");
      element.addClass("btn-outline-success");
      element.html("Subscribe");
    }
  })
</script>

app/views/message_rooms/new.html.erb
<h1 class="text-center my-5">New Message Room</h1>

<%= render 'form', message_room: @message_room %>

<%= link_to 'Back', message_rooms_path %>

app/views/message_rooms/show.html.erb
<div class="message-room">
  <h2 class="text-center my-3">Room title: "<%=@message_room.title%>"</h2>
  <%= link_to message_rooms_path do %>
    <div class="back-arrow text-dark"><</div>
  <% end %>

  <!-- show message dependent upon whose it is -->
  <div class="messages">
    <% @messages.each do |message| %>
        <%= render partial: "message", locals: {message: message, user: message.user} %>
    <% end %>
    <div class="panel-body hidden" id="new-message-target-<%= @message_room.id %>"></div>
  </div>

  <div class="message-input">
    <!-- only render the input if the user is subscribed -->
    <% if @subscribers.include?(current_user) %>
      <%= form_with(model: @message, remote: true) do |form| %>
        <div class="row mx-3 py-3">
            <%= form.text_field :body, class: "form-control col-sm-11 col-xs-10", id: "message-input", autocomplete: "off" %>
            <%= form.hidden_field :user_id, value: current_user.id %>
            <div class="btn btn-primary col-sm-1 col-xs-2" onclick="clearInput()" id="message-enter-button">Send</div>
        </div>
      <% end %>
    <% else %>
      <h4 class="py-3 text-center mx-auto">
        you must <%= link_to "subscribe",
                              message_rooms_subscribe_path(user_id: current_user.id, message_room_id: params[:id], redirect_to_page: true),
                              method: :post,
                              class:"btn btn-success subscribe-button" %>
        to contribute to this message room</h4>
    <% end %>
  </div>

  <!-- list those that are subscribed to this message room -->
  <div class="w-50 mx-auto my-5">
    <h4>Message room followed by:</h4>
    <ul>
      <% @subscribers.each do |sub| %>
        <li><%= sub.username %></li>
      <% end %>
    </ul>
  </div>
</div>

<!-- JS to submit form and clear for both click send and enter send -->
<!-- Last line is to make sure the messages box has scrolled t the bottom of messages -->
<script type="text/javascript">
  function clearInput() {
    $("form").submit()
    $("#message-input").val("");
  }

  $(document).on("keypress", function(e){
    if ( e.which == 13 ) {
      $("form").submit()
      $("#message-input").val("");
    }
  });

  $('.messages').scrollTop($('.messages')[0].scrollHeight);
</script>

app/views/message_rooms/subscribe.js.erb
$("#subscribed-chats").html("<%= j (render 'my_rooms', my_rooms: @my_rooms) %>")